services:
  postgres:
    image: 'postgres:16.1-alpine'
    environment:
      - 'POSTGRES_DB=reddit'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:7.2.4-alpine'
    ports:
      - '6379:6379'
