name: Gradle wrapper update
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  gradle-wrapper-upgrade:
    name: Bump Gradle Wrapper
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dependencies
        run: ./gradlew dependencies
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1