name: test

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main]

jobs:
  test-with-container:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:21.0.2
    steps:
      - name: add tar used for caching
        run: apk add --no-cache tar
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew test
