name: test

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main]

jobs:
  test-with-container:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:21.0.2
    steps:
      - name: add tar used for caching
        run: apk add --no-cache tar
      - uses: actions/checkout@v4
      - name: setup gradle cache
        uses: actions/cache@v4
        with:
          path: |
            /root/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: setup gradle wrapper cache
        uses: actions/cache@v4
        with:
          path: |
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - run: ./gradlew test
